# Generated by Django 2.1.5 on 2019-01-11 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lender_books', '0002_book_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
    ]
